resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:bf351b1dc0b089a7c539015ded959490e63ef96eae515900b491a5325483e077
  name: controller
  newName: 072298089782.dkr.ecr.us-east-2.amazonaws.com/mysql-database-operator

# Uncomment the below to use a private pull secret
#patches:
#- path: pull_secret.yaml
#  target:
#    kind: Deployment
