# permissions for end users to view adminconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminconnection-viewer-role
rules:
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - adminconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - adminconnections/status
  verbs:
  - get
