# permissions for end users to view databaseusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseuser-viewer-role
rules:
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - databaseusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - databaseusers/status
  verbs:
  - get
