---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - adminconnections
  - databases
  - databaseusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - adminconnections/finalizers
  - databases/finalizers
  - databaseusers/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.apps.cuppett.dev
  resources:
  - adminconnections/status
  - databases/status
  - databaseusers/status
  verbs:
  - get
  - patch
  - update
