name: CI

on:
  push:
    branches:
    - main
    - release-*
  pull_request:
    branches:
    - main
    - release-*

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        images:
        - 'mariadb:10.11'
        - 'mariadb:10.6'
        - 'mysql:8'
        kubernetes:
        - '1.29'
        - '1.30'
        - '1.31'

    name: make test ${{ matrix.images }} - K8s v${{ matrix.kubernetes }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run tests
      env:
        ENVTEST_K8S_VERSION: ${{ matrix.kubernetes }}
        MYSQL_IMAGE: ghcr.io/cuppett/${{ matrix.images }}
      run: |
        make test
