name: CI

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        images:
        - 'mariadb:10.11'
        - 'mariadb:10.6'
        - 'mysql:8'
        - 'mysql:5.7'
        kubernetes:
        - '1.25'
        - '1.26'
        - '1.27'

    name: Operator SDK ${{ matrix.images }} - K8s v${{ matrix.kubernetes }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run tests
      env:
        ENVTEST_K8S_VERSION: ${{ matrix.kubernetes }}
        MYSQL_IMAGE: ghcr.io/cuppett/${{ matrix.images }}
      run: |
        make test
